import type { Metadata } from "next";
// import "../styles/globals.css";
import "../styles/global.scss";
import Cursor from "@/components/shared/cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative antialiased font-satoshi ">
        <div
          className="pointer-events-none fixed inset-0 z-[9999] mix-blend-multiply"
          style={{
            backgroundImage: "url('/assets/images/noise.png')",
            backgroundRepeat: "repeat",
            // backgroundSize: "auto",
            backgroundSize: "500px",
          }}
        />
        <Cursor />
        <div>{children}</div>
      </body>
    </html>
  );
}
